fix github actions

diff --git a/.github/workflows/R-CMD-check.yaml b/.github/workflows/R-CMD-check.yaml
--- a/.github/workflows/R-CMD-check.yaml
+++ b/.github/workflows/R-CMD-check.yaml
@@ -33,116 +33,109 @@ jobs:
 
     steps:
     - name: Check out repo
-        uses: actions/checkout@v2
+      uses: actions/checkout@v2
 
-      - name: Set up R and install BiocManager
-        uses: grimbough/bioc-actions/setup-bioc@v1
-        if: matrix.config.image == null
-        with:
-          bioc-version: ${{ matrix.config.bioc }}
+    - name: Set up R and install BiocManager
+      uses: grimbough/bioc-actions/setup-bioc@v1
+      if: matrix.config.image == null
+      with:
+        bioc-version: ${{ matrix.config.bioc }}
 
-      - name: Set up pandoc (default version)
-        uses: r-lib/actions/setup-pandoc@v2
-        if: matrix.config.image == null && matrix.config.pandoc == null
+    - name: Set up pandoc (default version)
+      uses: r-lib/actions/setup-pandoc@v2
+      if: matrix.config.image == null && matrix.config.pandoc == null
 
-      - name: Set up pandoc (specified version)
-        uses: r-lib/actions/setup-pandoc@v2
-        if: matrix.config.image == null && matrix.config.pandoc != null
-        with:
-          pandoc-version: ${{ matrix.config.pandoc }}
+    - name: Set up pandoc (specified version)
+      uses: r-lib/actions/setup-pandoc@v2
+      if: matrix.config.image == null && matrix.config.pandoc != null
+      with:
+        pandoc-version: ${{ matrix.config.pandoc }}
 
-      - name: Set bitmapType
-        if: runner.os == 'macOS'
-        run: echo 'options(bitmapType = "cairo")' >> $HOME/.Rprofile
+    - name: Set bitmapType
+      if: runner.os == 'macOS'
+      run: echo 'options(bitmapType = "cairo")' >> $HOME/.Rprofile
 
-      - name: Install remotes and rmarkdown
-        run: |
-          install.packages(c('remotes', 'rmarkdown'))
-        shell: Rscript {0}
+    - name: Install remotes and rmarkdown
+      run: |
+        install.packages(c('remotes', 'rmarkdown'))
+      shell: Rscript {0}
 
-      - name: Test pandoc configuration
-        run: |
-          rmarkdown::pandoc_available()
-          rmarkdown::pandoc_version()
-          rmarkdown::pandoc_exec()
-          rmarkdown::pandoc_citeproc_args()
-          file.exists(file.path(dirname(rmarkdown::pandoc_exec()), "pandoc-citeproc"))
-          Sys.which("pandoc")
-          Sys.which("pandoc-citeproc")
-        shell: Rscript {0}
+    - name: Test pandoc configuration
+      run: |
+        rmarkdown::pandoc_available()
+        rmarkdown::pandoc_version()
+        rmarkdown::pandoc_exec()
+        rmarkdown::pandoc_citeproc_args()
+        file.exists(file.path(dirname(rmarkdown::pandoc_exec()), "pandoc-citeproc"))
+        Sys.which("pandoc")
+        Sys.which("pandoc-citeproc")
+      shell: Rscript {0}
 
-      - name: Query dependencies
-        run: |
-          saveRDS(remotes::dev_package_deps(dependencies = TRUE, repos = c(getOption('repos'), BiocManager::repositories())), 'depends.Rds', version = 2)
-        shell: Rscript {0}
+    - name: Query dependencies
+      run: |
+        saveRDS(remotes::dev_package_deps(dependencies = TRUE, repos = c(getOption('repos'), BiocManager::repositories())), 'depends.Rds', version = 2)
+      shell: Rscript {0}
 
-      - name: Cache R packages
-        if: runner.os != 'Windows' && matrix.config.image == null
-        uses: actions/cache@v1
-        with:
-          path: ${{ env.R_LIBS_USER }}
-          key: ${{ runner.os }}-bioc-${{ matrix.config.bioc }}-pandoc-${{ matrix.config.pandoc }}-${{ hashFiles('depends.Rds') }}
-          restore-keys: ${{ runner.os }}-bioc-${{ matrix.config.bioc }}-pandoc-${{ matrix.config.pandoc }}-
+    - name: Cache R packages
+      if: runner.os != 'Windows' && matrix.config.image == null
+      uses: actions/cache@v1
+      with:
+        path: ${{ env.R_LIBS_USER }}
+        key: ${{ runner.os }}-bioc-${{ matrix.config.bioc }}-pandoc-${{ matrix.config.pandoc }}-${{ hashFiles('depends.Rds') }}
+        restore-keys: ${{ runner.os }}-bioc-${{ matrix.config.bioc }}-pandoc-${{ matrix.config.pandoc }}-
+    - name: Install system dependencies (Linux)
+      if: runner.os == 'Linux'
+      env:
+        RHUB_PLATFORM: linux-x86_64-ubuntu-gcc
+      run: |
+        Rscript -e "remotes::install_github('r-hub/sysreqs')"
+        sysreqs=$(Rscript -e "cat(sysreqs::sysreq_commands('DESCRIPTION'))")
+        sudo -s eval "$sysreqs"
+        sudo apt-get update && sudo apt-get -y install libcurl4-openssl-dev libharfbuzz-dev libfribidi-dev
+    - name: Install system dependencies (macOS)
+      if: runner.os == 'macOS'
+      run: |
+        brew install harfbuzz
+        brew install fribidi
+    - name: Install dependencies
+      run: |
+        local_deps <- remotes::local_package_deps(dependencies = TRUE)
+        deps <- remotes::dev_package_deps(dependencies = TRUE, repos = BiocManager::repositories())
+        BiocManager::install(local_deps[local_deps %in% deps$package[deps$diff != 0]], Ncpu = 2L)
+        remotes::install_cran('rcmdcheck', Ncpu = 2L)
+      shell: Rscript {0}
 
-      - name: Install system dependencies (Linux)
-        if: runner.os == 'Linux'
-        env:
-          RHUB_PLATFORM: linux-x86_64-ubuntu-gcc
-        run: |
-          Rscript -e "remotes::install_github('r-hub/sysreqs')"
-          sysreqs=$(Rscript -e "cat(sysreqs::sysreq_commands('DESCRIPTION'))")
-          sudo -s eval "$sysreqs"
-          sudo apt-get update && sudo apt-get -y install libcurl4-openssl-dev libharfbuzz-dev libfribidi-dev
-      - name: Install system dependencies (macOS)
-        if: runner.os == 'macOS'
-        run: |
-          brew install harfbuzz
-          brew install fribidi
-      - name: Install dependencies
-        run: |
-          local_deps <- remotes::local_package_deps(dependencies = TRUE)
-          deps <- remotes::dev_package_deps(dependencies = TRUE, repos = BiocManager::repositories())
-          BiocManager::install(local_deps[local_deps %in% deps$package[deps$diff != 0]], Ncpu = 2L)
-          remotes::install_cran('rcmdcheck', Ncpu = 2L)
-        shell: Rscript {0}
+    - name: Session info
+      run: |
+        options(width = 100)
+        pkgs <- installed.packages()[, "Package"]
+        sessioninfo::session_info(pkgs, include_base = TRUE)
+      shell: Rscript {0}
 
-      - name: Session info
-        run: |
-          options(width = 100)
-          pkgs <- installed.packages()[, "Package"]
-          sessioninfo::session_info(pkgs, include_base = TRUE)
-        shell: Rscript {0}
+    - name: Build, Install, Check
+      uses: grimbough/bioc-actions/build-install-check@v1
 
-      - name: Build, Install, Check
-        uses: grimbough/bioc-actions/build-install-check@v1
+    - name: Run BiocCheck
+      uses: grimbough/bioc-actions/run-BiocCheck@v1
+      with:
+        arguments: '--no-check-bioc-views --no-check-bioc-help'
+        error-on: 'error'
 
-      - name: Run BiocCheck
-        uses: grimbough/bioc-actions/run-BiocCheck@v1
-        with:
-          arguments: '--no-check-bioc-views --no-check-bioc-help'
-          error-on: 'error'
+    - name: Show testthat output
+      if: always()
+      run: find check -name 'testthat.Rout*' -exec cat '{}' \; || true
+      shell: bash
 
-      - name: Show testthat output
-        if: always()
-        run: find check -name 'testthat.Rout*' -exec cat '{}' \; || true
-        shell: bash
+    - name: Upload check results
+      if: failure()
+      uses: actions/upload-artifact@master
+      with:
+        name: ${{ runner.os }}-bioc-${{ matrix.config.bioc }}-results
+        path: check
 
-      - name: Upload check results
-        if: failure()
-        uses: actions/upload-artifact@master
-        with:
-          name: ${{ runner.os }}-bioc-${{ matrix.config.bioc }}-results
-          path: check
-
-      - name: Test coverage
-        if: matrix.config.os == 'macOS-latest' && matrix.config.pandoc == null
-        run: |
-          install.packages("covr")
-          covr::codecov(token = "${{secrets.CODECOV_TOKEN}}")
-        shell: Rscript {0}
-
-      - name: Deploy
-        if: github.event_name == 'push' && github.ref == 'refs/heads/master' && matrix.config.os == 'macOS-latest' && matrix.config.pandoc == null
-        run: |
-          R CMD INSTALL .
-          Rscript -e "remotes::install_dev('pkgdown'); pkgdown::deploy_to_branch(new_process = FALSE)"
+    - name: Test coverage
+      if: matrix.config.os == 'macOS-latest' && matrix.config.pandoc == null
+      run: |
+        install.packages("covr")
+        covr::codecov(token = "${{secrets.CODECOV_TOKEN}}")
+      shell: Rscript {0}
